server.port=${SERVER_PORT:18081}
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/carcare}
spring.datasource.username=${DB_USERNAME:carcare}
spring.datasource.password=${DB_PASSWORD:carcare}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.sql.init.mode=${SQL_INIT_MODE:never}
spring.sql.init.data-locations=classpath:data.sql,classpath:data-postgresql.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

kakao.client-id=${KAKAO_CLIENT_ID:31a78ed0030ac205ddf12b4382b1b74a}
kakao.redirect-uri=${KAKAO_REDIRECT_URI:http://localhost:18081/oauth/kakao/callback}
