ALTER TABLE car_brands ALTER COLUMN id RESTART WITH 4;
ALTER TABLE cars ALTER COLUMN id RESTART WITH 7;
ALTER TABLE car_options ALTER COLUMN id RESTART WITH 9;
ALTER TABLE centers ALTER COLUMN id RESTART WITH 5;
ALTER TABLE schedule_drive ALTER COLUMN id RESTART WITH 4;
